services:
  web: 
    build: ./
    ports: 
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app
  
  link:
    image: mablhq/link-agent
    command: bin/link-agent --api-key ${API_KEY} --name joe-link

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    # volumes:
    #   - mongodb_data:/data/db
  
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins:/var/jenkins_home:rw

volumes:
  jenkins: